### ISSUE TITLE
Error applying kernel patch during provisioning

### ISSUE THREAD

**Issue by tnagyzambo** [mkaczanowski/packer-builder-arm#112]
Hello,

I've been trying to use the packer-builder-arm to make some Raspberry-Pi Ubuntu images with the PREEMPT_RT patch applied. I'm running into an issue when trying to apply the patch using `sudo dpkg -i /rt-deb/*.deb` in the provisioner. The patch applies fine on the hardware.

I think that it has something to do with the labeling of the partitions, which might be related to #37 but this is pretty far outside of my normal work so I'm not too sure.

Here is a [link](https://github.com/tnagyzambo/rpi-ubuntu-rt) to the project.

Any help or pointers would be appreciated, thanks!

The error:
```arm.ubuntu: Selecting previously unselected package linux-headers-5.4.83-rt51-v8+.
    arm.ubuntu: (Reading database ... 66795 files and directories currently installed.)
    arm.ubuntu: Preparing to unpack .../linux-headers-5.4.83-rt51-v8+_5.4.83-rt51-v8+-1_arm64.deb ...
    arm.ubuntu: Unpacking linux-headers-5.4.83-rt51-v8+ (5.4.83-rt51-v8+-1) ...
    arm.ubuntu: Selecting previously unselected package linux-image-5.4.83-rt51-v8+.
    arm.ubuntu: Preparing to unpack .../linux-image-5.4.83-rt51-v8+_5.4.83-rt51-v8+-1_arm64.deb ...
    arm.ubuntu: Unpacking linux-image-5.4.83-rt51-v8+ (5.4.83-rt51-v8+-1) ...
    arm.ubuntu: Selecting previously unselected package linux-libc-dev:arm64.
    arm.ubuntu: Preparing to unpack .../linux-libc-dev_5.4.83-rt51-v8+-1_arm64.deb ...
    arm.ubuntu: Unpacking linux-libc-dev:arm64 (5.4.83-rt51-v8+-1) ...
    arm.ubuntu: Setting up linux-headers-5.4.83-rt51-v8+ (5.4.83-rt51-v8+-1) ...
    arm.ubuntu: Setting up linux-image-5.4.83-rt51-v8+ (5.4.83-rt51-v8+-1) ...
==> arm.ubuntu: update-initramfs: Generating /boot/initrd.img-5.4.83-rt51-v8+
==> arm.ubuntu: Label writable not found in /dev/disk/by-label
==> arm.ubuntu: Warning: root device LABEL=writable does not exist
==> arm.ubuntu: W: mkconf: MD subsystem is not loaded, thus I cannot scan for arrays.
==> arm.ubuntu: W: mdadm: failed to auto-generate temporary mdadm.conf file.
==> arm.ubuntu: flash-kernel: deferring update (trigger activated)
==> arm.ubuntu: flash-kernel: deferring update (trigger activated)
    arm.ubuntu: Setting up linux-libc-dev:arm64 (5.4.83-rt51-v8+-1) ...
    arm.ubuntu: Processing triggers for flash-kernel (3.103ubuntu1~20.04.1) ...
==> arm.ubuntu: Unsupported platform.
==> arm.ubuntu: dpkg: error processing package flash-kernel (--install):
==> arm.ubuntu:  installed flash-kernel package post-installation script subprocess returned error exit status 1
==> arm.ubuntu: Errors were encountered while processing:
==> arm.ubuntu:  flash-kernel
==> arm.ubuntu: error while running provision hook: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
    arm.ubuntu: optional (please ignore) `fuser -k` failed with exit status 1:
Build 'arm.ubuntu' errored after 2 minutes 43 seconds: build was halted```

**Comment by mkaczanowski** [comment]
chroot environment is quite limited, and it's not a VM. (this is not the issue with the plugin)

Upgrading a kernel sometimes might work, for example, if that's just a simple binary replacement. But often, during the upgrade the initrd is being generated, dkms runs etc. adding additional steps that often are somewhat machine or system dependant.

The issue you encountered:
> ==> arm.ubuntu: W: mkconf: MD subsystem is not loaded, thus I cannot scan for arrays.
> ==> arm.ubuntu: W: mdadm: failed to auto-generate temporary mdadm.conf file.

is caused by madm that can't scan raid arrays (likely module on the host machine is not present). I'd advise you to upgrade the kernel on the first boot instead. This is:
1. in the provisioner download the latest kernel binary
2. in the [boot script](https://github.com/mkaczanowski/packer-builder-arm/tree/master/scripts) run `dpkg -i ...`
3. build the image
