### ISSUE TITLE
Add example for using flasher post-processor with Docker

### ISSUE THREAD

**Issue by realies** [mkaczanowski/packer-builder-arm#115]
It seems that the flasher post-processor is not part of https://docker.io/mkaczanowski/packer-builder-arm:latest
```
error initializing post-processor 'flasher': Unknown post-processor flasher
```
Is there a way to install the plugin inside the container, or make it built-in the Docker image?

**Comment by mkaczanowski** [comment]
> Is there a way to install the plugin inside the container, or make it built-in the Docker image?

you'd have to expose the plugin binary via volume. Or you can build on top of the `packer-builder-arm` image

**Comment by realies** [comment]
@mkaczanowski, thanks for the reply. Can we have an example, please?

**Comment by mkaczanowski** [comment]
PRs are most welcome :)

**Comment by realies** [comment]
@mkaczanowski to clarify, the flasher post-processor has to be built for the host architecture and the binary mounted to the docker image that runs packer-builder-arm?

**Comment by realies** [comment]
@mkaczanowski, what is the path at which the plugin will get detected?
