### ISSUE TITLE
Arm8 64 bit compatible

### ISSUE THREAD

**Issue by bcomnes** [mkaczanowski/packer-builder-arm#15]
Wondering if this works with Rpi3/4 Arm 8 (64 bit).  Didn't notice anything mentioned.  Any pointers appreciated.   Awesome work ✌️

**Comment by mkaczanowski** [comment]
yes it should work for aarch64. What you need to do is to change qemu binary in the config, see:
```
$ cat /proc/sys/fs/binfmt_misc/aarch64 
enabled
interpreter /usr/bin/qemu-aarch64-static
flags: F
offset 0
magic 7f454c460201010000000000000000000200b7
mask ffffffffffffff00fffffffffffffffffeffff
```

So in that case you should use `/usr/bin/qemu-aarch64-static`

**Comment by bcomnes** [comment]
Cool! That seemed to work.  I'll PR an example once I clean it up.
