### ISSUE TITLE
is a armv6l target build possible?

### ISSUE THREAD

**Issue by jopek** [mkaczanowski/packer-builder-arm#159]
it seems that even when using `packer-builder-arm/boards/raspberry-pi/raspbian.json` the command `uname -m` yields *`armv7l`*. is there a way to use the armv6l?
I am using packer-builder-arm to build pihole images which in turn downloads one of the  `https://github.com/pi-hole/FTL/releases` binaries. since the images are to be run on a raspberry pi zero (v.1.3) using an armv6l and not armv7l results in a segmentation fault... a workaround would be to "manually" download the v6-binary. but it's kind of ugly.

**Comment by diijkstra** [comment]
Works for me when `QEMU_CPU=arm1176` environment variable is set (in docker). This turns on the emulation of v6 CPU instead of v7 with ArchlinuxARM rpi1 image:

```
==> arm.archlinux.rpi1: Provisioning with shell script: /tmp/packer-shell214161071
    arm.archlinux.rpi1: armv6l unknown unknown
```

Shout out for [this StackOverflow answer](https://stackoverflow.com/questions/66116587/docker-buildx-mulitarch-armv6).
