### ISSUE TITLE
What is the difference between https://github.com/mkaczanowski/packer-builder-arm and https://github.com/solo-io/packer-builder-arm-image?

### ISSUE THREAD

**Issue by ipl31** [mkaczanowski/packer-builder-arm#2]
Hello,
I am checking out the project. Thanks for building this. In addition to this project I came across:
https://github.com/solo-io/packer-builder-arm-image

It does not appear that one is a fork of the other. I was wondering what the difference is. Is it just different implementations of the same idea?

I know this is not technically an issue, but I opened it as an issue because it might be a useful addition to the README if there are major differences or call outs between the two. 

Thanks

**Comment by mkaczanowski** [comment]
Hey,
I think this should answer your question:
https://github.com/hashicorp/packer/pull/8462

I'll add some info to the README.md
