### ISSUE TITLE
Image download from Google Drive

### ISSUE THREAD

**Issue by pedro-ricardo** [mkaczanowski/packer-builder-arm#210]
Hello there, thank you for this plugin. It works perfectly.

I have a problem with OrangePI though,
The official repository of OS images for [OrangePI 3](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/service-and-support/Orange-pi-3-LTS.html) seems to be a public Google Drive folder.

This is a problem because I can't find a url to put in `"file_urls"` that works.
I've tried to follow posts like [this](https://medium.com/@acpanjan/download-google-drive-files-using-wget-3c2c025a8b99) and managed to download the file using the terminal but no luck with doing it by the`"file_urls"` field.

- Orange PI 3 LTS [page](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/service-and-support/Orange-pi-3-LTS.html)
- Public google drive [Folder](https://drive.google.com/drive/folders/1ctuKgHNN9r517tiAv9GGGaR7UYQgZiXP)
- Information about the file:
    - Name: `Orangepi3-lts_3.0.0_debian_bullseye_server_linux5.16.17.7z`
    - FolderID: `1ctuKgHNN9r517tiAv9GGGaR7UYQgZiXP`
    - FileID: `1kPZg2Yc5W75itAgWfztHRuqM8IHAkRk2`

As expected everything works if I download the image first and point the local path in `"file_urls"`.

**Comment by dbast** [comment]
Yep, downloading before running packer and then referencing as local file is the way to go. Adding this to the README:

Downloads of the file_urls are done with the help of github.com/hashicorp/go-getter, which supports various protocols: local files, http(s) and various others, see https://github.com/hashicorp/go-getter#supported-protocols-and-detectors). Downloading via other protocols can be done by using other tools (curl, wget, rclone, ...) before running packer and referencing the downloaded files as local file in file_urls.
