### ISSUE TITLE
Skip checksum verification

### ISSUE THREAD

**Issue by smartYSC** [mkaczanowski/packer-builder-arm#346]
Is it possible to skip the `file_checksum` verification?

My image comes from a trusted source (it was built right before by a different packer run). Computing its checksrum and then checking it again requires quite some extra time while giving no benefit.

It would be nice if I could skip the checksum and use the image without verifying it before.

**Comment by michalfita** [comment]
Yes.
```hcl
file_checksum_type    = "none"
```

**Comment by smartYSC** [comment]
Thank you, works like a charm!
