### ISSUE TITLE
Ability to label filesystem

### ISSUE THREAD

**Issue by rmb938** [mkaczanowski/packer-builder-arm#37]
It would be useful to be able to label the partitions in the disk image.

This may be a bit difficult as each filesystem has it's own label utility.

**Comment by zartdinov** [comment]
I think you can do it in shell for now

**Comment by v4n6** [comment]
I added a PR with mkfs options. It should solve the problem of setting the label of newly created filesystems, But, doesn't change the existing. Will this cover the issue?
