### ISSUE TITLE
arm: chroot: failed to run command ‘/bin/sh’: No such file or directory

### ISSUE THREAD

**Issue by BaptisteAmato** [mkaczanowski/packer-builder-arm#44]
Hi,

The error I get is the following:
`arm: chroot: failed to run command ‘/bin/sh’: No such file or directory`

I tried to run the jetson-nano/ubuntu.json template, and am working on Ubuntu 18.04.

Best

**Comment by mkaczanowski** [comment]
fixed:
https://github.com/mkaczanowski/packer-builder-arm/commit/f2267387a6ec34e25ef52347fab4a474fff263cb
