### ISSUE TITLE
==> arm: Unknown host QEMU_IFLA type: 50

### ISSUE THREAD

**Issue by BaptisteAmato** [mkaczanowski/packer-builder-arm#47]
Hi,

I get several erros like this one during provisioning:
`
==> arm: Unknown host QEMU_IFLA type: XXX
`

Any idea where it comes from?

**Comment by mkaczanowski** [comment]
those are the qemu binfmt messages

**Comment by BaptisteAmato** [comment]
Does it mean everything related to qemu binfmt is about the image I'm building? I'm having a hard time understanding where the commands come from, the host or the newly created image...

**Comment by mkaczanowski** [comment]
packer-builder-arm chroot's to the image, so it's always a host (in a sense, there is no virtualization). binfmt + qemu is just a way to emulate different CPU architecture.

The problem is somewhere with your qemu or smth system related (not packer-builder-arm related) thus closing
