### ISSUE TITLE
SSH does not come up on rpi4 arch linux

### ISSUE THREAD

**Issue by faddat** [mkaczanowski/packer-builder-arm#59]
I am using this to build device images for [Starport](https://github.com/tendermint/starport).

It's my understanding that by default, ssh should be up, and I should be able to login as alarm/alarm. 

However, when I boot the device it **does** get an IP adddress, but **does not** start SSH, and I wanted to check in to see if I was missing anything basic.  

I added a

```bash
systemctl enable sshd
```

to the build process, but that has not improved the situation, builds still come without ssh.  

Any ideas?

Thank you!

**Comment by mkaczanowski** [comment]
> but does not start SSH,

I'd connect via UART and check whether the service is up.

> systemctl enable sshd

That should work, I checked the `ls -la /etc/systemd/system/multi-user.target.wants/` and the sshd symlink is there

---

To be honest this is not the issue of the packer-builder-arm, so closing the issue
