### ISSUE TITLE
Transfer Files into the image

### ISSUE THREAD

**Issue by Cyril-Nachbaur** [mkaczanowski/packer-builder-arm#74]
Hello,
First, Thank you a lot for this amazing work, this solution is very useful for a project of mine.

I am building an Image of Ubuntu for my Raspberry Pi 4.
I am configuring my image with a shell script executed by the json file, to have my custom app ready to use.
I would like to transfer some files from my host to the Emulated Raspberry during the packer build (to run some commands afterwards and have everything ready on my image).
How would it be possible if it is ?

Thanks a lot.

**Comment by mkaczanowski** [comment]
Here's the example how to copy the file: https://github.com/mkaczanowski/packer-builder-arm/blob/7d1d806e287d92540ecf462f65cb1055456fa687/boards/raspberry-pi-3/archlinuxarm.json#L47
