### ISSUE TITLE
Why do we need to mount `/dev/`?

### ISSUE THREAD

**Issue by daxmc99** [mkaczanowski/packer-builder-arm#85]
Came across this repo and I wanted to try out the pure docker build for MacOS. 

However, mounting `dev` with a privileged docker image is equivalent to running a script as root. 

Is this absolutely needed or is there a way to work around it?

**Comment by dbast** [comment]
A free loop device (`/dev/loopX`) is required to mount images inside docker. Docker itself does not provide any loop device, so mounting `/dev` from the host makes that possible.

**Comment by mkaczanowski** [comment]
@dbast explained it well. Elevating permissions is tricky and frankly speaking, the simplest option is to use a wider permission group (ie root, sudo), especially that some people use Mac, and others Linux.

If you're not comfortable with sudo/root option, you can always build stuff on top of the VM. For instance, there is a Vagrant test setup where you can do whatever you like while being isolated from the host system:
https://github.com/mkaczanowski/packer-builder-arm#troubleshooting

**Comment by daxmc99** [comment]
Thanks for the info! That makes sense
