### ISSUE TITLE
Coral DEV board build

### ISSUE THREAD

**Issue by Erokos** [mkaczanowski/packer-builder-arm#94]
Hi,
first of all thank you for your great work with this plugin, it already helped me build a Raspberry Pi image. However, I'm stuck on trying to build one for the Coral DEV board - https://coral.ai/software/#mendel-dev-board and because of my previous success I don't think the issue is with my own setup or OS (I'm using Ubuntu 20.04 within WSL2).

Based on the examples in the plugin I've initaiated the build using your docker image:
`docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build packer/coral.json`

I've first tried out this configuration,where I used the `reuse` option which seems the most logical for my use-case but then again I admit that I don't completely understand the image build methods :)

{
    "variables": {},
    "builders": [
        {
            "type": "arm",
            "file_urls": [
                "https://mendel-linux.org/images/enterprise/eagle/enterprise-eagle-20210204152958.zip"
            ],
            "file_checksum": "67db0f6af8d80f591ba5519ca586970f7fe063f2a4ea390b5af5c0bacb8361b9",
            "file_checksum_type": "sha256",
            "file_target_extension": "zip",
            "image_build_method": "reuse",
            "image_path": "coral.img",
            "image_size": "6G",
            "image_type": "dos",
            "image_partitions": [
                {
                    "name": "boot",
                    "type": "c",
                    "start_sector": "8192",
                    "filesystem": "vfat",
                    "size": "256M",
                    "mountpoint": "/boot"
                },
                {
                    "name": "root",
                    "type": "83",
                    "start_sector": "532480",
                    "filesystem": "ext4",
                    "size": "0",
                    "mountpoint": "/"
                }
            ],
            "image_chroot_env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
            ],
            "qemu_binary_source_path": "/usr/bin/qemu-aarch64-static",
            "qemu_binary_destination_path": "/usr/bin/qemu-aarch64-static"
        }
    ],
    "provisioners": [
        {
            "type": "shell",
            "script": "packer/setup.sh"
        }
    ]
}

This outputs:

`==> arm: Retrieving rootfs_archive
==> arm: Trying https://mendel-linux.org/images/enterprise/eagle/enterprise-eagle-20210204152958.zip?archive=false
==> arm: Trying https://mendel-linux.org/images/enterprise/eagle/enterprise-eagle-20210204152958.zip?archive=false&checksum=sha256%3A67db0f6af8d80f591ba5519ca586970f7fe063f2a4ea390b5af5c0bacb8361b9
==> arm: https://mendel-linux.org/images/enterprise/eagle/enterprise-eagle-20210204152958.zip?archive=false&checksum=sha256%3A67db0f6af8d80f591ba5519ca586970f7fe063f2a4ea390b5af5c0bacb8361b9 => /build/packer_cache/c71f32b8a43a0eadbd214dd75659b5f0fd3167a0.zip
    arm: unpacking /build/packer_cache/c71f32b8a43a0eadbd214dd75659b5f0fd3167a0.zip to coral.img
==> arm: error while copying file exit status 1: mv: cannot overwrite non-directory 'coral.img' with directory '/tmp/image629357766/enterprise-eagle-20210204152958'
==> arm:
Build 'arm' errored after 11 seconds 350 milliseconds: build was halted

==> Wait completed after 11 seconds 350 milliseconds

==> Some builds didn't complete successfully and had errors:
--> arm: build was halted

==> Builds finished but no artifacts were created.`

then I tried with the `new` build method option and the option is:

`arm: output will be in this color.

==> arm: Retrieving rootfs_archive
==> arm: Trying https://mendel-linux.org/images/enterprise/eagle/enterprise-eagle-20210204152958.zip?archive=false
==> arm: Trying https://mendel-linux.org/images/enterprise/eagle/enterprise-eagle-20210204152958.zip?archive=false&checksum=sha256%3A67db0f6af8d80f591ba5519ca586970f7fe063f2a4ea390b5af5c0bacb8361b9
==> arm: https://mendel-linux.org/images/enterprise/eagle/enterprise-eagle-20210204152958.zip?archive=false&checksum=sha256%3A67db0f6af8d80f591ba5519ca586970f7fe063f2a4ea390b5af5c0bacb8361b9 => /build/packer_cache/c71f32b8a43a0eadbd214dd75659b5f0fd3167a0.zip
    arm: creating an empty image coral.img
==> arm: dd output: 0+0 records in
==> arm: 0+0 records out
==> arm: 0 bytes copied, 7.26e-05 s, 0.0 kB/s
==> arm:
    arm: creating 2 dos partitions on coral.img
    arm: searching for empty loop device (to map coral.img)
    arm: mapping image coral.img to /dev/loop2
    arm: running mkfs
    arm: mounting /dev/loop2p2 to /tmp/943929984
    arm: mounting /dev/loop2p1 to /tmp/943929984/boot
    arm: unpacking /build/packer_cache/c71f32b8a43a0eadbd214dd75659b5f0fd3167a0.zip to /tmp/943929984
    arm: running extra setup
    arm: mounting /dev with: [mount --bind /dev /tmp/943929984/dev]
    arm: mounting /devpts with: [mount -t devpts /devpts /tmp/943929984/dev/pts]
    arm: mounting proc with: [mount -t proc proc /tmp/943929984/proc]
    arm: mounting binfmt_misc with: [mount -t binfmt_misc binfmt_misc /tmp/943929984/proc/sys/fs/binfmt_misc]
    arm: mounting sysfs with: [mount -t sysfs sysfs /tmp/943929984/sys]
    arm: running the provision hook
==> arm: Provisioning with shell script: packer/setup.sh
==> arm: error while running provision hook: Error uploading script: exit status 1
    arm: optional (please ignore) `fuser -k` failed with exit status 1:
Build 'arm' errored after 5 minutes 14 seconds: build was halted

==> Wait completed after 5 minutes 14 seconds

==> Some builds didn't complete successfully and had errors:
--> arm: build was halted

==> Builds finished but no artifacts were created.`

Do you have any suggestions why it can't take up and use my shell script to configure the image?
Any help would be appreciated, thanks in advance :)

**Comment by mkaczanowski** [comment]
the coral board has a peculiar image:
```
ls /
boot.img  boot.scr  dev  fsl-imx8mm-columbia.dtb  fsl-imx8mq-phanbell.dtb  fsl-imx8mq-yorktown.dtb  home.img  Image  initramfs.cpio.gz.uboot  lost+found  partition-table-16gb.img  partition-table-64gb.img  partition-table-8gb.img  proc  rootfs.img  sys  u-boot.imx  usr
```

likely if you combine `rootfs.img` and `partition-table-8gb.img` you'll get somewhat bootable rootfs image. In addition to that you'll have to setup boot partition (device tree files etc) correctly.

The setup of mendel linux for coral board is unusual, therefore won't work with `packer-builder-arm`.
